basic_blog/blog/urls.py
from django.urls import path

from .views import index, article

app_name = "blog"
urlpatterns = [
    path("", index, name="index"),
    path("<slug:slug>/", article, name="article"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from basic_blog.blog.views import index
from django.conf.urls.static import static

urlpatterns = [
    path("", index, name="home"),
    path("blog/", include("basic_blog.blog.urls", namespace="blog")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "contact",
        TemplateView.as_view(template_name="pages/contact.html"),
        name="contact",
    ),
    path(settings.ADMIN_URL, admin.site.urls),
    path("markdownx/", include("markdownx.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basic_blog/blog/models.py
from django.db import models
from django.conf import settings

from autoslug import AutoSlugField
from markdownx.models import MarkdownxField


class Article(models.Model):
    title = models.CharField(max_length=255)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="title")
    abstract = models.TextField(max_length=512)
    content = MarkdownxField()
    date_created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product_photos", null=True, blank=True)

    def __str__(self):
        return f"{self.title}"

basic_blog/blog/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from .models import Article


def index(request):
    articles = Article.objects.all().order_by("-date_created")

    paginator = Paginator(articles, 5)
    try:
        page_number = request.GET.get("page")
    except AttributeError:
        page_number = 1
    page_obj = paginator.get_page(page_number)
    image_absolute_url = request.build_absolute_uri('static/assets/img/django.png')
    context = {
        "articles": articles,
        "page_obj": page_obj,
        'image_absolute_url': image_absolute_url,
    }
    return render(request, "blog/index.html", context)


def article(request, slug):
    article = Article.objects.get(slug=slug)
    if article.image:
        image_absolute_url = request.build_absolute_uri(article.image.url)
    else:
        image_absolute_url = request.build_absolute_uri('static/assets/img/django.png')
    context = {"article": article, "image_absolute_url": image_absolute_url}
    return render(request, "blog/article.html", context)

basic_blog/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description"
          content="{% block description %}Articles sur développement d'applications Django{% endblock description %}"/>
    <meta name="author" content="" />
    <title>
      {% block title %}
        Blog Personnel - Antoine Rebillard
      {% endblock title %}
    </title>
    {% block opengraph_tags %}
      <meta property="og:title"
            content="Articles sur développement d'applications Django"/>
      <meta property="og:type" content="website" />
      <meta property="og:url" content="{{ request.build_absolute_uri }}" />
      <meta property="og:image" content="{{ image_absolute_url }}" />
      <meta property="og:site_name" content="Django Facile" />
    {% endblock opengraph_tags %}
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
          rel="stylesheet"
          type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
          rel="stylesheet"
          type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'home' %}">Django Facile</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false"
                aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:index' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'about' %}">A propos</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead"
            {% block background_image %}
            style="background-image: url('{% static "assets/img/home-bg.jpg" %}')"
            {% endblock background_image %}>
      <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="site-heading">
              {% block header_titles %}
                <h1>Django Facile</h1>
                <span class="subheading">Tutoriels et conseil pour débuter avec le framework Django</span>
              {% endblock header_titles %}
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- Main Content-->
    {% block content %}{% endblock %}
    <!-- Footer-->
    <footer class="border-top">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="http://github.com/antoine71"
                   target="_blank"
                   rel="noopener noreferrer">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="http://resume.arebillard.fr"
                   target="_blank"
                   rel="noopener noreferrer">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fas fa-file-lines fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <div class="small text-center text-muted fst-italic">
              Copyright &copy; <a href="https://resume.arebillard.fr">Antoine Rebillard</a> 2022, photos <a href="https://www.pexels.com/@cottonbro/">cottonbro</a> et <a href="https://www.pexels.com/@pixabay/">Pixabay</a>, thème <a href="https://startbootstrap.com">startbootstrap</a>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

basic_blog/templates/blog/article.html
{% extends 'base.html' %}
{% load static %}
{% load markdown_extras %}
{% block description %}
  {{ article.abstract }}
{% endblock description %}
{% block title %}
  {{ article.title }}
{% endblock title %}
{% block opengraph_tags %}
  <meta property="og:title" content="{{ article.title }}" />
  <meta property="og:type" content="article" />
  <meta property="og:url"
        content="{{ request.build_absolute_uri }}"/>
  <meta property="og:image" content="{{ image_absolute_url }}" />
  <meta property="og:site_name" content="Django Facile" />
{% endblock opengraph_tags %}
{% block content %}
  <article class="mb-4">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="post-preview">
            <h2 class="post-title">{{ article.title }}</h2>
            <p class="post-meta">
              Publié par {{ article.author.first_name }} {{ article.author.last_name }} le {{ article.date_created | date:"j F Y" }}
            </p>
          </div>
          {{ article.content | markdown | safe }}
        </div>
      </div>
    </div>
  </article>
{% endblock content %}

basic_blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <!-- Post preview-->
        {% if page_obj %}
          {% for article in page_obj %}
            <div class="post-preview">
              {% if article.image %}<img src="{{ article.image.url }}" alt="" class="img-fluid" style="max-width: 300px;">{% endif %}
              <a href="{% url 'blog:article' slug=article.slug %}">
                <h2 class="post-title">{{ article.title }}</h2>
                <h3 class="post-subtitle">{{ article.abstract }}</h3>
              </a>
              <p class="post-meta">
                Publié par
                <a href="#!">{{ article.author.first_name }} {{ article.author.last_name }}</a>
                le {{ article.date_created | date:"j F Y" }}
              </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
          {% endfor %}
        {% endif %}
        <!-- Pager-->
        {% if page_obj.has_next %}
          <div class="d-flex justify-content-end mb-4">
            <a href="?page={{ page_obj.next_page_number }}">
              <div class="btn btn-primary text-uppercase">Articles suivants</div>
            </a>
          </div>
        {% else %}
          <div class="d-flex justify-content-end mb-4">
            <div class="btn btn-primary text-uppercase">Fin des articles</div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

basic_blog/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}



{% block background_image %}style="background-image: url('{% static "assets/img/about-bg.jpg"%}')"{% endblock background_image %}

{% block header_titles %}
<h1>A propos de moi</h1>
<span class="subheading">Voici ce que je fais...</span>
{% endblock header_titles %}

{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Je suis un développeur passionné. J'ai découvert la programmation en 2021 avec <a href="https://www.openclassrooms.com/">Openclassrooms.com</a></p>
                <p>J'ai décidé de partager et de proposer des solutions simples, en français, aux problèmes les plus fréquemment rencontrés lors de l'apprentissage du framework Django.</p>                
                <p>Le code de ce site est libre de droit et est disponible <a href="https://github.com/antoine71/basic_blog">ici.</a></p>
            </div>
        </div>
    </div>
</main>


{% endblock content %}